### ISSUE TITLE
Spamming browser history

### ISSUE THREAD

**Issue by thetarnav** [solidjs/solid-playground#102]
The URL changes are doing scary things to my browser history. Wouldn't there be a way to debounce the URL updates, or do then only on idle? the [tsplayground](www.typescriptlang.org/play) seams to be more reasonable with those updates.

https://user-images.githubusercontent.com/24491503/166141983-7734d7a1-cf15-441b-b7b2-5d79f8ba47fa.mp4

**Comment by amoutonbrady** [comment]
Uhm interesting, we are using `history.replaceState`  and I though this was enough to mitigate this issue but turns out this is an ongoing issue in browser land and it's been there for almost 10 years! https://bugzilla.mozilla.org/show_bug.cgi?id=753264

I'm wondering if this is still necessary to sync the URL though. Perhaps just generating it when pushing the "share" button would be sufficient nowadays (as this is what's being store in the cloudflare KV store, it needs to exist at before being stored).

Thanks, I'll look into a solution
