### ISSUE TITLE
Add dependencies

### ISSUE THREAD

**Issue by snewell92** [solidjs/solid-playground#35]
I wanted to play and learn with solidjs, and the first thing was like "what does an App do, it routes. Yeah SPAs, they route". So I found [this lib](https://github.com/Seanmclem/solidjs-router) but to my chagrin the playground doesn't have anything like [what some others](https://ellie-app.com/new) do by giving an [interface to install](https://codesandbox.io/s/new). I can just play locally tho. I guess I could just switch to codesandbox... Why don't we just use a pre configured/forkable codesandbox with solidjs in it? Then this would be moot!

Very interested in solidjs.... keep it up friend.

**Comment by snewell92** [comment]
Could be closed if we link [to an existing codesandbox](https://codesandbox.io/s/solid-tsx-starter-x2u2h) or make our own.

**Comment by amoutonbrady** [comment]
I'm not entirely sure I understand what you are asking for.

1. I do agree that generally speaking, CodeSandBox, StackBlitz, Repl.it, etc.. provide a better UX and DX but you have to keep in mind that to my knowledge those are literally businesses. We don't really aim to provide a replacement for it but rather just a logical step where you start in our playground with everything working out of the box for reproduction or quick experiments and then you can move to CodeSandBox for buffier examples. That being said, we do have a basic CSB export in our playground.
2. If I understand your issue, you want to use external libraries in our playground? This is possible. The only 2 issues are:
  - There's no TS support for external libraries
  - There's no router working because of the way we inject the compiled code in the preview pane
  Here's an example: https://playground.solidjs.com/?hash=-1053980493&version=1.0.0
3. That template you linked was actually made by me. I should probably update it to latest solid. Thanks for reminding me!

I hope that it can shed some lights on the purpose of the playground.
