### ISSUE TITLE
CSS files by URL

### ISSUE THREAD

**Issue by edemaine** [solidjs/solid-playground#76]
In testing Solid Bootstrap, it'd be really nice to be able to include the Bootstrap CSS in the output. Two natural interfaces:

* Button for adding CSS by URL
* `import` the CSS URL in main.ts. Several build processes support this, and the CSS is already available from NPM and [via skypack](https://cdn.skypack.dev/-/bootstrap@v5.1.3-FTeCMkp7MfkGFnMJQMvv/dist=es2019,mode=raw/dist/css/bootstrap.css) so this would be especially convenient. 

Happy to discuss/brainstorm further, here or in Discord, but wanted to write down this request, having needed it a couple times this week.

**Comment by modderme123** [comment]
Does something like https://playground.solidjs.com/?hash=-147837099&version=1.2.6 work for you?

**Comment by edemaine** [comment]
Ah, yes, that does work pretty well. The above e.g. import would be nicer, but only slightly, so not a priority.

Thanks!

**Comment by amoutonbrady** [comment]
I had an idea the other day. Maybe we could have some sort of settings popup page (initially Wordle made me think of it but in retrospective, every sandbox has that).
On the model of Codepen, we could have two text areas, one for inserting stuff in the head of the webview and one for adding stuff at the end of the body.
The issue is that I wonder if there are any security issues...

**Comment by modderme123** [comment]
This works now: https://playground.solidjs.com/anonymous/6d4825f2-8531-4588-8d34-c1383b9b4591
